name = "website-reports"
main = "src/index.ts"
compatibility_date = "2026-02-15"
workers_dev = false

[triggers]
crons = ["0 6 1 * *"]

[vars]
REPORT_TIMEZONE = "Europe/Dublin"

[[r2_buckets]]
binding = "REPORTS_BUCKET"
bucket_name = "website-reports-reports"

[[d1_databases]]
binding = "REPORTS_DB"
database_name = "website-reports-db"
database_id = "ef0a03f1-0108-47fb-898d-7b4a5d5aed44"
